#!/bin/sh

TARGET=$1
TARNAME=$(basename ${TARGET})
git submodule update;
git archive -o ${TARGET} HEAD
cp etc/knomod_version BASE_VERSION
u8_gitversion etc/knomod_version > VERSION
u8_gitversion etc/knomod_version -full > FULL_VERSION
u8_gitbranch > BRANCH
tar -rf ${TARGET} VERSION BASE_VERSION FULL_VERSION BRANCH
("cd" libzip-source; git archive --prefix=libzip-source/ -o ../libzip.tar HEAD);
tar --concatenate --file=${TARGET} libzip.tar
rm libzip.tar
